#pragma once
#include <stdint.h>
extern "C" {
// Queued blackbox gate with original addtoetime before drawing and tmr_reset
// after drawing, BEFORE the100-raw-tick/key wait. Dismissal does not reset time.
uint32_t cc_modal_radio_begin(uint32_t before_draw_clock,uint32_t after_draw_clock);
// Browser split: sample the first clock, draw synchronously, then sample the
// second clock and call wait_start exactly once if draw_queued returned1.
uint32_t cc_modal_radio_draw_queued(uint32_t before_draw_clock);
void cc_modal_radio_wait_start(uint32_t after_draw_clock);
// dotower1D6D..1D90. Hardware interrupt/vector changes are host boundaries.
// Return1 => write current140-byte result record, then enter runtower;
// return0 => original preexisting/reset diagnostic skipped tower body.
uint32_t cc_modal_tower_enter(uint32_t clock);
// Original runtowerB66..B89, AFTER result write and BEFORE child UI/calibration.
void cc_modal_tower_audio();
// dotower1D96..1E3F AFTER runtower/getstartfile return. Host must already have
// applied child status, selected STARTLOC fields, and DOS interrupt9 fields.
// Reinitializes graphics memory, palette, observer repair branch, timer/latches.
void cc_modal_tower_return(uint32_t clock);
// Original main-frame269B..26A3; also called if tower_enter returned0.
void cc_modal_tower_finish();
// Monotonic palette event: [sequence,attribute8=63,16*(DACindex,R,G,B)].
// Six-bit final DAC values; generated by mode reset/distortcolor/setcolors255,
// then optional source distcolors when tripflag1 bit0 is set.
uint32_t* cc_modal_tower_palette();
}
